[env:ATmega328PB]
platform = atmelavr
board = ATmega328PB
framework = arduino
upload_protocol = usbasp
upload_flags = -Pusb -e
monitor_speed = 115200
lib_deps = 
	sandeepmistry/LoRa@^0.8.0
	annem/ADXL362@^1.5
